<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="ScriptLab.Tests/**/*.cs" />
        <Compile Remove="ScriptLab.ScriptAssets/**/*.cs" />
        <Compile Remove="ScriptLab.Analyzers/**/*.cs" />
        <Compile Remove="Samples/**/*.ash.cs" />
        <None Include="Samples/**/*.ash.cs" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    </ItemGroup>

</Project>
